name       : mage
version    : 1.7.1
release    : 4
source     :
    - https://github.com/magefile/mage/archive/v1.7.1.tar.gz : 1ee01601ba5728b5a0cda61f5e3bcdd227d9ae202a49acbcce69583e2ca6cc9a
license    : Apache-2.0
component  : programming.tools
summary    : Mage is a make/rake-like build tool using Go. You write plain-old go functions, and Mage automatically uses them as Makefile-like runnable targets.
description: |
    Mage is a make/rake-like build tool using Go. You write plain-old go functions, and Mage automatically uses them as Makefile-like runnable targets.
extract    : no
builddeps  :
    - golang
rundeps    :
    - golang
setup      : |
    mkdir -p github.com/magefile/mage
    tar xf $sources/v${version}.tar.gz -C github.com/magefile/mage --strip-components 1
    ln -s $workdir src
build      : |
    cd src/github.com/magefile/mage
    GOPATH=$workdir go build -o magebin
install    : |
    install -Dm00755 github.com/magefile/mage/magebin $installdir/usr/bin/mage
    # Drop the symlink and our binary
    rm github.com/magefile/mage/magebin src
    install -dm00755 $installdir/%libdir%/golang/src/github.com/magefile/mage
    cp -R $workdir/github.com/magefile/mage/* $installdir/%libdir%/golang/src/github.com/magefile/mage/
